export const studentPageURL = '#/dashboard/consultees';
export const SearchByOption = 'div[class="flex-filter-options"] > div:nth-child(1) div[class="Select-multi-value-wrapper"]';
export const SelectField = '.Select-placeholder';
export const NumberofStudent = '.table-responsive tbody tr';
export const StudentName = 'tr:first-of-type td[class="results-td padding-set image-hold"] div';
export const userName = 'tr:first-of-type > td:nth-of-type(2)[class="results-td padding-set"] >div';
export const Email = 'tr:first-of-type > td:nth-of-type(3)[class="results-td padding-set"] >div';
export const DateOfRegistratioin = 'tr:first-of-type > td:nth-of-type(4)[class="results-td padding-set"] >div';
export const ThreeDot = 'tr:nth-of-type(1) i[class="fas fa-ellipsis-h"]';
export const SendTemporaryPassword = 'div[aria-hidden="false"] >button[class = "dropdown-itemes-in-results dropdown-item"]';
export const DeleteStudent = 'div[aria-hidden="false"] >button[class = "dropdown-item"]';